### PR TITLE
Hover nearest element on mouse movement

### PR DESCRIPTION
**Pull request by sigmapi**
Two commits so far:

1.Improved javascript performance

- Eliminated individual (per svg element) mouse position/action event handlers
- Added MouseHandler to set unique global mouse position/action event handlers on svg surface
- Disabled pointer-events on non-interactive elements
- Enabled ids for interactive elements for faster access

2. New feature: Hover nearest element on mouse movement

### CODE REVIEW

**Comment by sigmapi** [comment]
Things to do:
- When using the nearest element feature, some times a point might be under the tooltip area. This should be fixed.

- Not high priority but for some shapes the stroke width should be taken into account. Currently it's not, but it's not a priority

**Comment by davidgohel** [comment]
Hi, while testing the PR I noticed one issue about the cursor position or the selected points

When in full page, also in Rmd, the area of the ggiraph output has to scrool (or "I noticed I can see the issue when I scrooled)

The highlighted point should be close to my mouse, not at the bottom.

Capture d’écran 2022-09-17 à 15 58 29

Capture d’écran 2022-09-17 à 15 58 46


````
library(ggplot2)
library(ggiraph)

dat <- mtcars
dat$carname <- row.names(mtcars)
gr <- ggplot(data = dat) +
  geom_point_interactive(
    aes(
      x = wt, y = qsec, color = disp,
      tooltip = paste(carname, disp, sep = "\n"),
      data_id = carname
    ),
    size = 5,
    hover_nearest = TRUE
  ) +
  theme_minimal()
x <- girafe(ggobj = gr, options = list(
  opts_zoom(max = 4), opts_selection(only_shiny = FALSE)
))

x

````

**Comment by sigmapi** [comment]
Update:
- Fixed the issue above
- Blocked the tooltip/hove/nearest element actions on mousedown/wheel
- Also the tooltip is cleared on same events
- Set the pointer cursor while panning/zooming/lasso

**Comment by sigmapi** [comment]
Update:
- check that tooltip rect does not contain the element's rect
- moved functions from nearest.js to geom.js

**Comment by davidgohel** [comment]
Awesome work as usual

let's merge

**Pull request closed without merging**
