### PR TITLE
fix: ensure compatibility with upcoming ggplot2 v3.4.3

### PR DESCRIPTION
**Pull request by sigmapi**
Compatibility with upcoming ggplot2 v3.4.3:
- Re-implemented interactive guides
- Fixed geom_label_interactive

### CODE REVIEW

**Comment by teunbrand** [comment]
Hi there,

This is just an update that we've set a release date for the ggplot2 version that includes the guide changes, and it is set to 12 February.  If you'd like to test this against the release candidate, you can install it via the code below:

```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

The progress of the release can be tracked in https://github.com/tidyverse/ggplot2/issues/5588

**Comment by davidgohel** [comment]
many thanks @teunbrand I'll have a look soon (hopefully next week)

**Comment by teunbrand** [comment]
This is just a friendly reminder that the release is due soon.

**Comment by davidgohel** [comment]
thanks @teunbrand, I know I know! Don't think I am not very stressed because of that :) 

But at least you can say to CRAN team you warned us long time ago, this should be enough for the CRAN team to accept your new release. 

Then we will receive an email saying ggiraph will be removed from cran if we don't fix quickly things

**Comment by teunbrand** [comment]
Aw sorry I didn't mean to stress you out! If you need any input please let me know

**Comment by davidgohel** [comment]
@teunbrand thank you, it should be ok. I think it's just a matter of few hours of work.

**Pull request closed without merging**
